### ISSUE TITLE
Feature Idea: Make over/undertime visible

### ISSUE THREAD

**Issue by mhutter** [vshn/odootools#116]
Goal: When browsing the monthly (or maybe also weekly) reports, make days with over/under time easily discernible.

- [ ] Align the "Worked hours" and "Overtime hours" columns
- [ ] Highlight over/under time (with colors)

**Comment by ccremer** [comment]
WDYM with "Align the "Worked hours" and "Overtime hours" columns", can you elaborate?

> Highlight over/under time (with colors)

What kind of colors would you use? Green for making overtime, red for undertime? Making too much overtime isn't good either, both from financial, legal and a health PoVs.

**Comment by mhutter** [comment]
> WDYM with "Align the "Worked hours" and "Overtime hours" columns", can you elaborate?

Right now it's visibly hard to make out what days are over- or under time, because the numbers do not align at all.

I quickly tried simply aligning the columns to the right but of course this does not work well with non-monospaced fonts.

The usual solution for this kind of problems (e.g. in accounting software) is to have the sign (Vorzeichen) aligned to the left (using `:before` in CSS, and only if it's negative), and the number (using a monospaced font) to the right.

This makes it very easily readable.

---

> What kind of colors would you use? Green for making overtime, red for undertime? Making too much overtime isn't good either, both from financial, legal and a health PoVs.

Absolutely true, but when I check Odootools, I want to know whether I made over- or under time, and how my total looks like, not whether I had a healthy or financially viable month ;-)

**Comment by ccremer** [comment]
First part - makes sense, we can improve that with your suggestion

Second - 
Alright, lets ignore the semantic psychological impact of the colors for now.
I was thinking about the colors, and since we have 1-2 colorblind people at vshn, we probably should avoid red/green. I was reading up on https://davidmathlogic.com/colorblind and think the one of the suggested color patterns could do it:
#005AB5, blueish, for overtime
#DC3220, reddish, for undertime
(https://davidmathlogic.com/colorblind/#%23005AB5-%23DC3220)
Alternatively, we could save a colorblind-flag in the cookies, but that may be overengineering.

Also, do you think it makes sense to only highlight with colors after a certain threshold? e.g. 5% of the daily max -> 24min over- or undertime in 8h day (3% would be 15min). Because I think that very small over- or undertime is not really worth highlighting IMO.

**Comment by ccremer** [comment]
> not whether I had a healthy or financially viable month ;-)

Just to be clear: our accounting people use the same views, so they are actually interested in how much someone makes overtime :)

**Comment by mhutter** [comment]
> I was thinking about the colors, and since we have 1-2 colorblind people at vshn, we probably should avoid red/green

Yes I thought the same. Maybe there is an option with symbols as well? Did not have a concrete idea though.

> Also, do you think it makes sense to only highlight with colors after a certain threshold? e.g. 5% of the daily max -> 24min over- or undertime in 8h day (3% would be 15min). Because I think that very small over- or undertime is not really worth highlighting IMO.

I had the same idea but failed to come up with reasonable thresholds :D

I'll try to work out a proposal and let you know.

**Comment by ccremer** [comment]
> Yes I thought the same. Maybe there is an option with symbols as well? Did not have a concrete idea though.

Emojis :) 🚨 for undertime, 🚀 for overtime

**Comment by ccremer** [comment]
This has now been implemented
